version: '3.8'

services:
  atprotoblog:
    image: ghcr.io/arcestia/atprotoblog:latest
    container_name: atprotoblog
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - ATP_SERVICE=https://pds.skiddle.id
      - ATP_IDENTIFIER=skiddle.id
      - ATP_DID=did:plc:kbpcqituf5ku6xorxo2wzdee
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: atprotoblog-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  redis_data:
    name: atprotoblog-redis-data