version: '3.8'

services:
  atprotoblog:
    image: ghcr.io/arcestia/atprotoblog:latest
    container_name: atprotoblog
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: atprotoblog-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped

volumes:
  redis_data:
    name: atprotoblog-redis-data